version: "3.8"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      BOT_TOKEN: $BOT_TOKEN  # defaults to None
      DATABASE_URL: $DATABASE_URL  # defaults to None
      OWNER_ID: $OWNER_ID
